# This is a basic workflow to help you get started with Actions

name: Autobahn

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Try to run server
        run: |
          cd $GITHUB_WORKSPACE/examples/websocket-echo/
          cargo build
          ROCKET_ADDRESS=0.0.0.0 cargo run &
        shell: bash

      - name: Run Autobahn|Testsuite
        run: |
          #until nc localhost 8000 -w 0; do sleep 1; done
          sleep 1
          docker run --add-host localhost:$(ip addr show docker0 | grep -Po 'inet \K[\d.]+') \
          -v ${{ github.workspace }}/.github/autobahn:/config \
          -v ${{ runner.temp }}:/reports \
          crossbario/autobahn-testsuite \
          wstest -m fuzzingclient -s /config/fuzzingclient.json
          for $file in ${{ runner.temp }}/servers/*.json
            do [[ $(jq ".behavior" $file) == "\"OK\"" ]]
          done
        shell: bash
      - name: test output
        run: |
          ls ${{ runner.temp }}/servers
